'''
=================================================
Milestone 1

Nama  : Mardi Wicaksana
Batch : CODA-RMT-0016

Program ini dibuat untuk mengambil data penjualan steam key di website itemku dengan melihat produk, keterangan, harga
=================================================
'''

In [51]:
import pandas as pd
import time

# Web Scraping
from selenium import webdriver
from bs4 import BeautifulSoup

In [ ]:
namaproduk = []
keterangan = []
harga = []
terjual = []

driver = webdriver.Edge()

for page in range(1,4):
    url = f"https://www.itemku.com/game-key/browse/steam?page={page}" ##melakukan automasi pindah page
    driver.get(url)
    time.sleep(5)
    html = driver.page_source
    soup = BeautifulSoup(html, "html.parser")


    boxes = soup.find_all("a",{"class":"block h-full"})
    #Ambil code data item dari inspect element browser
    for box in boxes:
        elnama_produk = box.find("h2",{"class":"text-lg text-[#1B1B1B] font-semibold600 line-clamp-2"})
        el_keterangan = box.find("div",{"class":"mt-1 text-lg text-suva-grey line-clamp-2"})
        el_harga = box.find("div",{"class":"text-xl text-[#F46200] font-bold font-itemkuV2"})
        el_terjual = box.find("div",{"class":"text-base text-suva-grey"})

        try:
            namaproduk.append(elnama_produk.get_text())
        except:
            namaproduk.append(None)

        try:
            keterangan.append(el_keterangan.get_text())
        except:
            keterangan.append(None)

        try:
            harga.append(el_harga.get_text())
        except:
            harga.append(None)

        try:
            terjual.append(el_terjual.get_text())
        except:
            terjual.append(None)


driver.quit()


df = pd.DataFrame()

df["namaproduk"] = namaproduk
df["keterangan"] = keterangan
df["harga"] = harga
df["terjual"] = terjual

##Data Cleansing
df = df.drop_duplicates(subset=["namaproduk"]) 
df["harga"] = df["harga"].str.replace("Rp", "").str.replace(" ", "").str.replace(".", "").astype(int)
df["terjual"] = df["terjual"].str.replace("terjual", "").str.replace(" ", "").astype(int)
df["keterangan"] = df["keterangan"].str.replace("•", "")

df.to_csv("P0-CODA16-RMT-M1-MARDI_WICAKSANA.csv")

In [60]:
df

,namaproduk,keterangan,harga,terjual
0,Red Dead Redemption 2: Ultimate Edition (PC) S...,Steam Akun Global,219043,4
1,Poppy Playtime - Chapter 2 (PC) Steam Sharing ...,Steam Sharing Account Global,20000,1
2,Random Key (PC) Steam Key Global,Steam Random Steam Key Global,1199,15501
3,Minecraft Java & Bedrock Edition (PC) Microsof...,Microsoft Store Key Global,270000,4037
4,Random Epic 1 Key (PC) Steam Key Global,Steam Random Steam Key Global,25000,3588
...,...,...,...,...
139,NARUTO X BORUTO Ultimate Ninja STORM CONNECTIO...,Steam Sharing Account Global,35000,8
140,Teardown: Ultimate Edition (PC) Steam Sharing ...,Steam Sharing Account Global,35000,8
141,God of War Ragnarök (PC) Steam Sharing Account...,Steam Sharing Account Global,35000,8
142,Feed and Grow: Fish (PC) Steam Sharing Account...,Steam Sharing Account Global,35000,8
143,Call of Duty®: Black Ops III - Zombies Chronic...,Steam Sharing Account Global,35000,8

In [54]:
df.head()

,namaproduk,keterangan,harga,terjual
0,Red Dead Redemption 2: Ultimate Edition (PC) S...,Steam Akun Global,219043,4
1,Poppy Playtime - Chapter 2 (PC) Steam Sharing ...,Steam Sharing Account Global,20000,1
2,Random Key (PC) Steam Key Global,Steam Random Steam Key Global,1199,15501
3,Minecraft Java & Bedrock Edition (PC) Microsof...,Microsoft Store Key Global,270000,4037
4,Random Epic 1 Key (PC) Steam Key Global,Steam Random Steam Key Global,25000,3588

In [55]:
df.tail()

,namaproduk,keterangan,harga,terjual
139,NARUTO X BORUTO Ultimate Ninja STORM CONNECTIO...,Steam Sharing Account Global,35000,8
140,Teardown: Ultimate Edition (PC) Steam Sharing ...,Steam Sharing Account Global,35000,8
141,God of War Ragnarök (PC) Steam Sharing Account...,Steam Sharing Account Global,35000,8
142,Feed and Grow: Fish (PC) Steam Sharing Account...,Steam Sharing Account Global,35000,8
143,Call of Duty®: Black Ops III - Zombies Chronic...,Steam Sharing Account Global,35000,8

In [56]:
df.describe()

               harga       terjual
count     143.000000    143.000000
mean   152030.188811    230.594406
std    212010.177202   1376.909323
min       777.000000      1.000000
25%     35000.000000     10.000000
50%     45000.000000     19.000000
75%    200500.000000     43.500000
max    947014.000000  15501.000000

In [57]:
df.shape

(143, 4)

In [58]:
df.nunique()

namaproduk    143
keterangan     14
harga          83
terjual        62
dtype: int64

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 143 entries, 0 to 143
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   namaproduk  143 non-null    object
 1   keterangan  143 non-null    object
 2   harga       143 non-null    int32
 3   terjual     143 non-null    int32
dtypes: int32(2), object(2)
memory usage: 4.5+ KB